services:
  backend:
    restart: always
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    networks:
      - bus
    deploy:
      mode: replicated
      replicas: 2
networks:
  bus:
